- name: install apt fail2ban packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - fail2ban

- name: override the basic fail2ban configuration with custom jail.local file
  copy:
    src: ../files/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Restart fail2ban
  service:
    name: 'fail2ban'
    state: 'restarted'
