- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port 5622"
  notify: "Restart sshd"

- name: Restart sshd
  service:
    name: sshd
    state: restarted
