---

- name: restart postgres
  docker_container:
    env:
      POSTGRES_PASSWORD: "{{ docker_postgres__superuser_password }}"
    image: "{{ docker_postgres__image }}"
    name: "{{ docker_postgres__name }}"
    ports:
      - "{{ docker_postgres__port }}:5432"
    pull: true
    restart_policy: always
    state: "{{ postgres_state }}"
    restart: yes
    user: "{{uid}}:{{gid}}"
    volumes:
      - "{{ docker_postgres__home }}/conf:/etc/postgresql"
      - "{{ docker_postgres__home }}/data:/var/lib/postgresql/data"
      - "/data/postgres/etc/locale.gen:/etc/locale.gen"
      - "/data/postgres/entrypoint.sh:/entrypoint.sh"
