---

- name: Install Fail2Ban from package
  package:
    name: fail2ban
    state: latest
    update_cache: yes

- name: Override the basic fail2ban configuration with custom jail.local file
  copy:
    src: ../files/jail_debian.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban
