- name: Add the user 'postgres' with a bash shell, appending the group 'postgres'
  user:
    name: postgres
    shell: /bin/bash
    groups: postgres
    append: yes

- name: check user's UID 
  getent:
    database: passwd
    key: postgress

- debug:
    var: getent_passwd
