- name: Remove home directory
  file:
    state: absent
    path: "{{ docker_postgres__home }}"
  when: docker_postgres__remove_existing_home_dir

- name: Create directories
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(0777) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    recurse: yes
  with_items: "{{ docker_postgres__directories }}"

- name: Copy pg_hba config
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ docker_postgres__home }}/conf/pg_hba.conf"
    owner: root
    group: root
    mode: 0664

- name: Copy postgresql config
  template:
    src: "postgresql.conf.j2"
    dest: "{{ docker_postgres__home }}/conf/postgresql.conf"
    owner: root
    group: root
    mode: 0664

- name: Copy entrypoint
  copy:
    src: entrypoint.sh
    owner: root
    group: root
    mode: 0777
    dest: "/data/postgres/entrypoint.sh"

- name: Override locale.gen
  copy:
    src: locale.gen
    dest: /data/postgres/etc/locale.gen
    owner: root
    group: root
    mode: 0644

- name: Run postgres container
  docker_container:
    name: "{{ docker_postgres__name }}"
    image: "{{ docker_postgres__image }}"
    entrypoint: "/entrypoint.sh"
    command: --config_file=/etc/postgresql/postgresql.conf --hba_file=/etc/postgresql/pg_hba.conf
    pull: "{{ docker_postgres__pull_image }}"
    restart_policy: always
    network_mode: "{{ docker_postgres__network_mode }}"
    networks: "{{ docker_postgres__networks }}"
    expose:
    - 5432
    ports: "{{ docker_postgres__ports }}"
    user: root:root
    env: "{{ docker_postgres__default_env | combine(docker_postgres__env) }}"
    volumes: "{{ docker_postgres__directory_volumes + docker_postgres__file_volumes }}"
    log_driver: "{{ docker_postgres__log_driver }}"
    state: started

- name: Wait for postgres to accept connections
  wait_for:
    host: 127.0.0.1
    port: 5432
    state: started
    timeout: 30
  register: postgres_running
  until: postgres_running is success
  retries: 10
