- name: Remove home directory
  file:
    state: absent
    path: "{{ docker_postgres__home }}"
  when: docker_postgres__remove_existing_home_dir

- name: Create directories
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(0777) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    recurse: yes
  with_items: "{{ docker_postgres__directories }}"

- name: Copy pg_hba config
  copy:
    content: "{{ docker_postgres__pg_hba_conf }}"
    dest: "{{ docker_postgres__home }}/conf/pg_hba.conf"

- name: Copy postgresql config
  copy:
    content: "{{ docker_postgres__postgresql_conf }}"
    dest: "{{ docker_postgres__home }}/conf/postgresql.conf"

- name: Run postgres container
  docker_container:
    name: "{{ docker_postgres__name }}"
    image: "{{ docker_postgres__image }}"
    command: --config_file=/etc/postgresql/postgresql.conf --hba_file=/etc/postgresql/pg_hba.conf
    pull: "{{ docker_postgres__pull_image }}"
    restart_policy: always
    network_mode: "{{ docker_postgres__network_mode }}"
    networks: "{{ docker_postgres__networks }}"
    expose:
    - 5432
    ports: "{{ docker_postgres__ports }}"
    user: root:root
    env: "{{ docker_postgres__default_env | combine(docker_postgres__env) }}"
    volumes: "{{ docker_postgres__directory_volumes + docker_postgres__file_volumes }}"
    log_driver: "{{ docker_postgres__log_driver }}"
    state: started
