- name: Create the postgres groups
  group:
    name: "{{ postgres_local_group }}"
  notify: restart postgres

- name: Create the postgres user
  user:
    name: "{{ postgres_local_user }}"
    shell: /bin/false
    groups: "{{ postgres_local_group }}"
    create_home: no
    password_lock: yes
    expires: -1
  notify: restart postgres

- name: Get postgres user info
  getent:
    database: passwd
    key: "{{ postgres_local_user }}"
    split: ":"

- name: Get postgres group info
  getent:
    database: group
    key: "{{ postgres_local_group }}"
    split: ":"

- name: Get uid
  set_fact:
    uid: "{{ getent_passwd[postgres_local_user][1] }}"
    gid: "{{ getent_group[postgres_local_group][1] }}"
